_prefs: 
  mapid: ''
  saveCenter: false
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -75.8647
  - 40.2413
  - 10
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: 
  - boundingbox
  - water
  - landmark_polygon
  - buildings
  - admin_lines
  - trans_linear
  - highway_labels
  - place_labels
  - highway_overlay
  - trans_linear_labels
  - vector_point_labels2
  - vector_point_labels3
maxzoom: 19
minzoom: 0
name: MQ Carto Style
source: "http://mq-nms-render-vector-stg-la01.ihost.aol.com:8080/tiles/tile.json"
styles: 
  - base.mss
  - water.mss
  - polygonal.mss
  - admin.mss
  - transportation.mss
  - roads_class_0.mss
  - highway_shield.mss
  - place_label.mss
  - transportation_label.mss
  - point_label2.mss
  - linear_label2.mss
  - point_label3.mss
template: ''
