_prefs: 
  mapid: ''
  saveCenter: false
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -75.8647
  - 40.2413
  - 10
description: ''
format: "png8:m=h"
interactivity_layer: ''
metatile: 1
layers:
  - boundingbox
  - water
  - water_linear
  - vector_polygonal_geometry
  - buildings
  - vector_linear_county
  - states
  - countries
  - trans_linear
  - highway_labels
  - place_labels
  - highway_overlay
  - trans_linear_labels
  - vector_point_labels2
  - vector_point_labels3
maxzoom: 19
minzoom: 0
name: MQ Carto Style
source: "tmsource:///home/pnorman/mq-carto-style-vector/mq-carto-style.tm2source"
styles: 
  - base.mss
  - water.mss
  - polygonal.mss
  - admin.mss
  - transportation.mss
  - place_label.mss
  - highway_shield.mss
  - transportation_label.mss
  - point_label2.mss
  - linear_label2.mss
  - point_label3.mss
template: ''
